### ISSUE TITLE
Reference problem in WPF environment

### ISSUE THREAD

**Issue by JakobFerdinand** [manuelroemer/Nullable#20]
When using the library in a WPF environment it´s not possible to add a reference to the included types.
I found that problem with my own library and was hoping, that you solved it somehow but I can recreate the issue with your project.

I created a [sample project](https://github.com/rzlsoftware/CodeOnlyNugetPackageTest) to recreate the issue.
The branch [nullable](https://github.com/rzlsoftware/CodeOnlyNugetPackageTest/tree/nullable) shows the problem with your library.

Its a simple console application that also includes a WPF `User Control`.
![image](https://user-images.githubusercontent.com/16666458/114677928-0b04d800-9d0b-11eb-9d63-9274bc8b95f3.png)

```cs
using System;
using System.Diagnostics.CodeAnalysis;

namespace TheWPFClient
{
    class Program
    {
        [AllowNull] private readonly string OptionalValue;

        static void Main(string[] args)
        {
            Console.WriteLine("Hello beatiful World!");
        }
    }
}
```
When compiling the code that build error accours:
```
Program.cs(8,10,8,19): error CS0246: The type or namespace name 'AllowNullAttribute' could not be found (are you missing a using directive or an assembly reference?)
Program.cs(8,10,8,19): error CS0246: The type or namespace name 'AllowNull' could not be found (are you missing a using directive or an assembly reference?)
```
If you delete the usercontrol the error is gone.

**Comment by chucker** [comment]
This may be related to #11

**Comment by JakobFerdinand** [comment]
Oh thank you!
Following you discussion to [microsoft/CsWin32#7](https://github.com/microsoft/CsWin32/issues/7) guided me to the solution.

It´t the same problem with the `temp` project files during build and I have to add the following property in my project:
```xml
<IncludePackageReferencesDuringMarkupCompilation>true</IncludePackageReferencesDuringMarkupCompilation>
```

**Comment by manuelroemer** [comment]
Glad that this resolved your issue!
I decided to pin #11 so that it is easier to discover in the future.
