### ISSUE TITLE
Can you add package to support InAttribute for netstandard1.0 as target

### ISSUE THREAD

**Issue by AlexRadch** [manuelroemer/Nullable#23]
When I use `ref readonly` and `in parameter` in package for `netstandard1.0` target, compiler return error `Predefined type 'System.Runtime.InteropServices.InAttribute' is not defined or imported`.

Can you add new package like Nullable to support `ref readonly` and `in parameter` for `netstandard1.0`.

Thanks.

**Comment by manuelroemer** [comment]
Hey, sorry to disappoint, but that's something that I'm not going to tackle because I don't have the time/personal need for it at the moment. But please feel free to build on this repository to do it yourself (or my IsExternalInit repo, because it's less complex configuration-wise).
